tasks:
  - init: |
      docker run -it --rm \
        --volume /var/run/docker.sock:/var/run/docker.sock \
        --volume "$(pwd)":/usr/src/code/appwrite:rw \
        --entrypoint="install" \
        appwrite/appwrite:latest \
        --httpPort="8080" \
        --httpsPort="443" \
        --interactive=0

ports:
  - port: 8080
    onOpen: open-preview
    visibility: public
  - port: 443
    onOpen: ignore
    visibility: public
  - port: 3001
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - ms-azuretools.vscode-docker
